# docker-compose.yml

services:
  backend:
    build: ./backend
    container_name: job_tracker_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: postgres:15
    container_name: job_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hasan099
      POSTGRES_DB: job_tracker_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: job_tracker_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data:
