name: Run Backend Tests

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    # Поднимаем Postgres как сервис db
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hasan099
          POSTGRES_DB: job_tracker_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Переменные окружения для runner-шагов и для вашего приложения
    env:
      # runner-шаги подключаются к published порту на localhost
      DB_HOST: localhost
      DATABASE_URL: postgresql://postgres:hasan099@localhost:5432/job_tracker_db
      SECRET_KEY: supersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h $DB_HOST -U postgres; do
            echo "Waiting for PostgreSQL at $DB_HOST..."
            sleep 2
          done

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term-missing
